name: Build and Push Docker Image & Deploy to AWS S3

on: 
  push:
    branches: ["main", "master"]

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Log in to Docker Hub 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_AWSproject_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AWSproject_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_AWSproject_USERNAME }}/cloude-images:latest
          #האוטומציה שלנו!!